[package]
name = "cargo-crate"
version = "0.0.0"
edition = "2021"
description = "tbd"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
